# New ports collection makefile for:	gnome-do-plugin-alias
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Assign alternate names to items

DO_PLUGIN=	alias

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
