#!/bin/sh
#
# Merge local ports with FreeBSD ports
#
# Files are automatically copied, files that need to be merged by hand are
# listed on stdout.

PORTSDIR=${PORTSDIR:=/var/cache/portshaker/freebsd}

# Unexpand any expanded VCS tag (e.g. $Id$) in $1 and write the result in $2.
unsubstitute_keywords()
{
	sed -E -e 's#\$(FreeBSD|Id|MCom):[^\$]*\$#$\1$#g' < $1 > $2
}

copy_noid()
{
	while read file_name
	do
		dir_name=`basename "${file_name}"`

		if [ ! -d ${dir_name} ]; then
			mkdir "${dir_name}" || exit 1
		fi

		unsubstitute_keywords "${PORTSDIR}/${file_name}" "${file_name}"
	done
}

for directory
do
	echo "MFC ${PORTSDIR}/${directory} -> ${directory}"
	find $directory -type f  ! -regex '.*/\.svn.*' | copy_noid
done

