#!/bin/sh
#
# Merge local ports with upstream (use after a merge in the FreeBSD ports
# tree).
#
# Files are automatically copied, files that need to be merged by hand are
# listed on stdout.

PORTSDIR=${PORTSDIR:=/var/cache/portshaker/freebsd}

remove_id()
{
	sed -e 's|\$\(FreeBSD\)[^\$]*\$|\1|g' < $1 > $2
}

compare_noid()
{
	while read file_name
	do

		if [ -e "${PORTSDIR}/${file_name}" ]; then
			remove_id "${file_name}" "${tomerge_noid}"
			remove_id "${PORTSDIR}/${file_name}" "${current_noid}"

			cmp -s "${current_noid}" "${tomerge_noid}"
			if [ $? -eq 0 ]; then
				cp "${PORTSDIR}/${file_name}" "${file_name}"
			else
				echo ${file_name}
				#diff  -u "${file_name}" "${PORTSDIR}/${file_name}"
			fi
		fi
	done
}

current_noid=`mktemp -t MFC`
tomerge_noid=`mktemp -t MFC`

for directory
do
	find $directory -type f  ! -regex '.*/\.svn.*' | compare_noid
done

rm -f "${current_noid}" "${tomerge_noid}"
