# New ports collection makefile for:	gnome-do-plugin-stock-quote
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Get live stock quotes from Google Finance

DO_PLUGIN=	stockquote

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
