# New ports collection makefile for:	gnome-do-plugin-eog-slideshow
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Play slideshows in Eye of GNOME

DO_PLUGIN=	eogslideshow

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
