# New ports collection makefile for:	mono-nat
# Date created:				20090202
# Whom:					pneumann@gmail.com
#
# $FreeBSD$
#

PORTNAME=	mono-nat
PORTVERSION=	1.0
CATEGORIES=	net
MASTER_SITES=	http://monotorrent.com/Files/

MAINTAINER=	mono@FreeBSD.org
COMMENT=	Port forwarding library for .NET

BUILD_DEPENDS=	mono:${PORTSDIR}/lang/mono
RUN_DEPENDS=	mono:${PORTSDIR}/lang/mono

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
