# New ports collection makefile for:	gnome-do-plugin-gnome-screenshot
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Take screenshots with optional delay

DO_PLUGIN=	gnomescreenshot

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
