# New ports collection makefile for:	gnome-do-plugin-vinagre
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Browse your VNC Viewer bookmarks and connect to remote servers

DO_PLUGIN=	vinagre

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
