# New ports collection makefile for:	mono-addins
# Date created:		2008-12-21
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTNAME=	mono-addins
PORTVERSION=	0.4
CATEGORIES=	devel
MASTER_SITES=	http://mono.ximian.com/monobuild/preview/sources/${PORTNAME}/

MAINTAINER=	bsd-sharp@googlegroups.com
COMMENT=	Framework for creating extensible applications

USE_ZIP=	yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_GNOME=	gtksharp20 gnomehack

MAN1=		mautil.1

.include <bsd.port.mk>
