# New ports collection makefile for:	gnome-do-plugin-google-docs
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Search documents, spreadsheets, and presentations on Google Docs

DO_PLUGIN=	googledocs

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
