# New ports collection makefile for:	nemo
# Date created:		2008-08-24
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTNAME=	nemo
PORTVERSION=	0.2.3
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	x11-fm
MASTER_SITES=	http://www.iola.dk/nemo/downloads/
#MASTER_SITE_SUBDIR=
#PKGNAMEPREFIX=
#PKGNAMESUFFIX=
#DISTNAME=
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	bsd-sharp@googlegroups.com
COMMENT=	A calendar-based file browser

USE_BZIP2=	yes
USE_GNOME=	gnomesharp20

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
