# New ports collection makefile for:	bareftp
# Date created:		2008-12-20
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTNAME=	bareftp
PORTVERSION=	0.2.2
CATEGORIES=	ftp
MASTER_SITES=	http://www.bareftp.org/release/

MAINTAINER=	mono@FreeBSD.org
COMMENT=	File transfer client

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_GNOME=	gnomehack gnomesharp20
INSTALLS_ICONS=	yes
USE_GETTEXT=	yes

CONFIGURE_ENV=	GMSGFMT=msgfmt

.include <bsd.port.mk>
