# New ports collection makefile for:	monotorrent
# Date created:				20090202
# Whom:					pneumann@gmail.com
#
# $FreeBSD$
#

PORTNAME=	monotorrent
PORTVERSION=	0.70
CATEGORIES=	net-p2p
MASTER_SITES=	http://monotorrent.com/Files/

MAINTAINER=	mono@FreeBSD.org
COMMENT=	Bittorrent library for .NET

BUILD_DEPENDS=	mono:${PORTSDIR}/lang/mono
RUN_DEPENDS=	mono:${PORTSDIR}/lang/mono

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
