# New ports collection makefile for:	gnome-do-plugin-gnome-terminal
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Run commands and open new terminals

DO_PLUGIN=	gnometerminal

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
