# New ports collection makefile for:	pdfmod
# Date created:		2009-07-28
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTNAME=	pdfmod
PORTVERSION=	0.3
CATEGORIES=	print
MASTER_SITES=	GNOME

MAINTAINER=	romain@blogreen.org
COMMENT=	A tool for modifying PDF documents

USE_BZIP2=	yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_GNOME=	gnomehack gnomesharp20
USE_GETTEXT=	yes

.include <bsd.port.mk>
