# New ports collection makefile for:	gnome-do-plugin-google-calculator
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Perform calculations, and currency/quantity conversions

DO_PLUGIN=	googlecalculator

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
