# New ports collection makefile for:	gnome-do-plugin-woof
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Send files and folders at blazing speed to Pidgin contacts on your local network

DO_PLUGIN=	woof

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
