# New ports collection makefile for:	gnome-do-plugin-launchpad
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Search various Launchpad properties (e.g. code, bugs, people)

DO_PLUGIN=	launchpad

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
