# New ports collection makefile for:	gnome-do-plugin-squeeze-center
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Control Logitech Squeezebox and Transport audio players

DO_PLUGIN=	squeezecenter

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
