# New ports collection makefile for:	gnome-do-plugin-gnome-dictionary
# Date created:		2009-07-12
# Whom:			Romain Tartiere <romain@blogreen.org>
#
# $FreeBSD$
#

PORTVERSION=	0
CATEGORIES=	deskutils

COMMENT=	Look up word definitions in GNOME Dictionary

DO_PLUGIN=	gnomedictionary

MASTERDIR=	${.CURDIR}/../../deskutils/gnome-do-plugins

.include "${MASTERDIR}/Makefile"
