#!/bin/sh
#
# Merge from trunk

PAGER=${DIFF_PAGER:=${PAGER:=less}}

usage()
{
	cat << EOT >&2
usage:
  $0 -c M:N...
  $0 -r M[,N...]
EOT
	exit 1
}

# Ensure the repository is up-to-date before doing anything.
if ! svn update; then
	echo "*** Repository update failed!" >&2
	exit 1
fi

out=`svn status | grep -v '^?'`
if [ -n "${out}" ]; then
	echo "*** Repository has local modifications!" >&2
	exit 1
fi

_c=""
_r=""

args=`getopt c:r: $*`
if [ $? -ne 0 ]; then
	usage
fi
set -- $args

for i
do
	case "$i" in
		-c) _c="$2"; shift; shift;;
		-r) _r="$2"; shift; shift;;
		--) shift; break;;
	esac
done

if [ -z "${_c}${_r}" -o -n "${_c}" -a -n "${_r}" ]; then
	usage
fi

repo_root=`svn info | awk ' $1 == "URL" { print $3 } '`
repo_trunk=`echo "${repo_root}" | sed -e 's|/branches/.*|/trunk|'`
repo_branch=`echo "${repo_root}" | sed -e 's|.*/branches/\([^/]*\).*|\1|'`

if [ -z "${repo_branch}" ]; then
	echo "*** MFT is intended to be run from a branch" >&2
	exit 1
fi

source=""
if [ -n "${_c}" ]; then
	svn merge -c "${_c}" ${repo_trunk}
	source="changeset ${_c}"
else
	svn merge -r "${_r}" ${repo_trunk}
	source="revision ${_r}"
fi

if [ $? -eq 0 ]; then
	ans=""
	while [ "$ans" != "yes" -a "$ans" != "no" ]; do
		svn diff | ${PAGER}
		echo -n "Commit this? (yes/no) "
		read ans
	done
	if [ "$ans" = "yes" ]; then
		svn commit -m "(${repo_branch}) MFT from ${source}."
	fi
fi

